{
 "title": "Broker Stats",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Top Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message Rate",
   "type": "timeseries",
   "description": "Number of messages per second, averaged across all brokers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(broker_websocket_messages_total{class=\"data\"}[1h]))"
    }
   ]
  },
  {
   "title": "Active Sockets",
   "type": "timeseries",
   "description": "Active sockets across all brokers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(broker_websocket_sockets_active[1h]))"
    }
   ]
  },
  {
   "title": "Max Message Throughput",
   "type": "stat",
   "description": "The maximum messages per second handled with a resolution of 1 minute",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time( sum(rate(broker_websocket_messages_total{class=\"data\"}[2m]))[$__range:1m] )"
    }
   ]
  },
  {
   "title": "Message Delivery",
   "type": "gauge",
   "description": "Percent of messages that are successfully delivered",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum(rate(broker_websocket_messages_total{class=\"data\", direction=\"egress\"}[5m])) - sum(rate(broker_websocket_messages_failed{class=\"data\", direction=\"egress\"}[5m])) ) / sum(rate(broker_websocket_messages_total{class=\"data\", direction=\"egress\"}[5m]))"
    }
   ]
  },
  {
   "title": "Message Receipt",
   "type": "gauge",
   "description": "Percent of messages that are successfully processed from clients. ",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum(rate(broker_websocket_messages_total{class=\"data\", direction=\"ingress\"}[5m])) - sum(rate(broker_websocket_messages_failed{class=\"data\", direction=\"ingress\"}[5m])) ) / sum(rate(broker_websocket_messages_total{class=\"data\", direction=\"ingress\"}[5m]))"
    }
   ]
  },
  {
   "title": "Max Websocket Throughput",
   "type": "stat",
   "description": "The maximum websockets per second handled with a resolution of 1 minute",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time( sum(rate(broker_websocket_sockets_total[2m]))[$__range:1m] )"
    }
   ]
  },
  {
   "title": "Max Concurrent Sockets",
   "type": "stat",
   "description": "The maximum concurrent websockets seen in the current time range",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(broker_websocket_sockets_active))"
    }
   ]
  },
  {
   "title": "Approx. Websocket Total ",
   "type": "stat",
   "description": "An approximate amount of unique websockets seen over the current time range",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(broker_websocket_sockets_total[$__range])))"
    }
   ]
  },
  { "title": "Per Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Message Rate",
   "type": "barchart",
   "description": "Number of messages per second, by broker",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (instance) (round(rate(broker_websocket_messages_total{class=\"data\"}[1h])))"
    }
   ]
  },
  {
   "title": "Active Sockets",
   "type": "barchart",
   "description": "Active sockets by broker",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (instance) (broker_websocket_sockets_active)"
    }
   ]
  },
  {
   "title": "Delivery/Receipt Success",
   "type": "barchart",
   "description": "The percentage of messages that have been successfully delivered and received, per broker",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) ((rate(broker_websocket_messages_total{class=\"data\", direction=\"egress\"}[5m]) - rate(broker_websocket_messages_failed{class=\"data\", direction=\"egress\"}[5m]) ) / rate(broker_websocket_messages_total{class=\"data\", direction=\"egress\"}[5m]))"
    },
    {
     "expr": "sum by (instance) ((rate(broker_websocket_messages_total{class=\"data\", direction=\"ingress\"}[5m]) - rate(broker_websocket_messages_failed{class=\"data\", direction=\"ingress\"}[5m]) ) / rate(broker_websocket_messages_total{class=\"data\", direction=\"ingress\"}[5m]))"
    }
   ]
  }
 ]
}