{
 "title": "Cloud Stats",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "Unique api queries by day",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "\nselect date_trunc('day', timestamp) as \"time\", count(distinct project_id)\nfrom sockets\ngroup by 1\norder by 1\n"
    }
   ]
  },
  {
   "title": "Total api queries by day",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "\nselect date_trunc('day', timestamp) as \"time\", count(project_id)\nfrom sockets\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "New Signups",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', consumers.created_at) as \"time\", count(distinct uuid)\nfrom consumers\ngroup by date_trunc('day', consumers.created_at)\norder by date_trunc('day', consumers.created_at) \n"
    }
   ]
  },
  {
   "title": "New Projects",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', projects.created_at) as \"time\", count(distinct uuid)\nfrom projects\ngroup by date_trunc('day', projects.created_at)\norder by date_trunc('day', projects.created_at) \n"
    }
   ]
  },
  {
   "title": "Cumulative Signups",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    date_trunc('day', consumers.created_at) as day,\n    count(1)\n  from consumers\n  group by 1\n  order by 1\n)\n\nselect\n  day as time,\n  sum(count) over (order by day asc rows between unbounded preceding and current row)\nfrom data"
    }
   ]
  },
  {
   "title": "Cumulative API queries ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    date_trunc('day', timestamp) as day,\n    count(1)\n  from sockets\n  group by 1\n  order by 1\n)\n\nselect\n  day as time,\n  sum(count) over (order by day asc rows between unbounded preceding and current row)\nfrom data"
    }
   ]
  }
 ]
}