{
 "title": "Nomad Overview",
 "description": "Nomad Cluster stats",
 "tags": [
  "nomad",
  "cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime, datacenter)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster (Totals)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "(sum(nomad_client_allocated_cpu)+sum(nomad_client_unallocated_cpu)) * 1000000",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(nomad_client_allocated_cpu) * 1000000",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(nomad_client_unallocated_cpu) * 1000000",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory usage across all clients",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(nomad_client_host_memory_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(nomad_client_host_memory_free)",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(nomad_client_host_memory_used)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(nomad_client_host_memory_available)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 9 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(nomad_client_host_disk_size)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(nomad_client_host_disk_available)",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(nomad_client_host_disk_size) - sum(nomad_client_host_disk_available)",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Allocations ($datacenter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_cpu{datacenter=~\"$datacenter\"}/(nomad_client_unallocated_cpu{datacenter=~\"$datacenter\"}+nomad_client_allocated_cpu{datacenter=~\"$datacenter\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_memory{datacenter=~\"$datacenter\"}/(nomad_client_unallocated_memory{datacenter=~\"$datacenter\"}+nomad_client_allocated_memory{datacenter=~\"$datacenter\"})"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 18 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_disk{datacenter=~\"$datacenter\"}/(nomad_client_unallocated_disk{datacenter=~\"$datacenter\"}+nomad_client_allocated_disk{datacenter=~\"$datacenter\"})"
    }
   ]
  }
 ]
}