{
 "title": "Service Stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_total_percent, exported_job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "stat",
   "description": "Currently active",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_summary_running{exported_job=~\"[[service]]\"})"
    }
   ]
  },
  {
   "title": "Starting",
   "type": "stat",
   "description": "In startup",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_summary_starting{exported_job=~\"[[service]]\"})"
    }
   ]
  },
  {
   "title": "Queued",
   "type": "stat",
   "description": "Pending allocations",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_summary_queued{exported_job=~\"[[service]]\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "bargauge",
   "description": "Allocations which experienced a failure in the current time range",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (task_group) (delta(nomad_nomad_job_summary_failed{exported_job=~\"[[service]]\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{task_group}}"
    }
   ]
  },
  {
   "title": "Lost",
   "type": "bargauge",
   "description": "Allocations which were lost by Nomad",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (task_group) (delta(nomad_nomad_job_summary_lost{exported_job=~\"[[service]]\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{task_group}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU cycles consumed per task",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum by (task) (nomad_client_allocs_cpu_total_ticks{exported_job=~\"[[service]]\", task!~\"connect-proxy.*\"}) * 1000000",
     "legendFormat": "{{task}}"
    },
    {
     "expr": "sum(nomad_client_allocs_cpu_allocated{exported_job=~\"[[service]]\"}) * 1000000"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (task) (nomad_client_allocs_memory_usage{exported_job=~\"[[service]]\", task!~\"connect-proxy.*\"})",
     "legendFormat": "{{task}}"
    },
    {
     "expr": "sum(nomad_client_allocs_memory_allocated{exported_job=~\"[[service]]\"})"
    }
   ]
  },
  { "title": "Public Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Status",
   "type": "bargauge",
   "description": "Per ingress status of the service",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (proxy) (haproxy_backend_status{proxy=~\"consul-[[service]]\\\\d+\"}) - ignoring (state) sum by (proxy) (haproxy_backend_status{proxy=~\"consul-[[service]]\\\\d+\", state=\"DOWN\"}))",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "stat",
   "description": "Total ingress traffic known to the public ingress",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_backend_bytes_in_total{proxy=~\"consul-[[service]]\\\\d+\"})",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Egress",
   "type": "stat",
   "description": "Total egress traffic known to the public ingress",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_backend_bytes_out_total{proxy=~\"consul-[[service]]\\\\d+\"})",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "timeseries",
   "description": "All responses sent by the service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (code) (ceil(rate(haproxy_backend_http_responses_total{proxy=~\"consul-[[service]]\\\\d+\"}[5m])))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Current active connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max_over_time( sum(haproxy_backend_current_sessions{proxy=~\"consul-[[service]]\\\\d+\"})[$__rate_interval:] )",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "description": "Various network timing averages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(haproxy_backend_connect_time_average_seconds{proxy=~\"consul-[[service]]\\\\d+\"})",
     "legendFormat": "connect"
    },
    {
     "expr": "avg(haproxy_backend_response_time_average_seconds{proxy=~\"consul-[[service]]\\\\d+\"})",
     "legendFormat": "response"
    },
    {
     "expr": "avg(haproxy_backend_queue_time_average_seconds{proxy=~\"consul-[[service]]\\\\d+\"})",
     "legendFormat": "queue"
    },
    {
     "expr": "avg(haproxy_backend_total_time_average_seconds{proxy=~\"consul-[[service]]\\\\d+\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "timeseries",
   "description": "Total amount of downtime in seconds over the current timescale, rounded",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (proxy) (round(increase(haproxy_backend_downtime_seconds_total{proxy=~\"consul-[[service]]\\\\d+\"}[$__rate_interval])))",
     "legendFormat": "{{proxy}}"
    }
   ]
  }
 ]
}