{
 "title": "Service Adoption Tracker",
 "description": "Tracks the adoption and stats of v1 and v2 services side by side",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Top Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Adoption",
   "type": "stat",
   "description": "Percentage of V1 (left) and V2 (right) connections, over the current timescale",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (max_over_time( sum(haproxy_backend_current_sessions{proxy=~\"consul-bridge.*\"})[$__rate_interval:] ) / (max_over_time( sum(haproxy_backend_current_sessions{proxy=~\"consul-bridge.*\"})[$__rate_interval:] ) + max_over_time( sum(haproxy_backend_current_sessions{proxy=~\"consul-api-proxy.*\"})[$__rate_interval:] ) ))"
    },
    {
     "expr": "100 * (max_over_time( sum(haproxy_backend_current_sessions{proxy=~\"consul-api-proxy.*\"})[$__rate_interval:] ) / (max_over_time( sum(haproxy_backend_current_sessions{proxy=~\"consul-bridge.*\"})[$__rate_interval:] ) + max_over_time( sum(haproxy_backend_current_sessions{proxy=~\"consul-api-proxy.*\"})[$__rate_interval:] ) ))"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Bridge Connections (V1)",
   "type": "timeseries",
   "description": "Total active V1 connections smoothed over 5 minute intervals",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max_over_time( sum(haproxy_backend_current_sessions{proxy=~\"consul-bridge.*\"})[$__rate_interval:] )"
    }
   ]
  },
  {
   "title": "Relay Connections (V2)",
   "type": "timeseries",
   "description": "Total active V2 connections smoothed over 5 minute intervals",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max_over_time( sum(haproxy_backend_current_sessions{proxy=~\"consul-api-proxy.*\"})[$__rate_interval:] )"
    }
   ]
  },
  {
   "title": "HTTP Responses (V1)",
   "type": "timeseries",
   "description": "Broken down by status code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (code) (round(rate(haproxy_backend_http_responses_total{proxy=~\"consul-bridge.*\"}[1m])))"
    }
   ]
  },
  {
   "title": "HTTP Responses (V2)",
   "type": "timeseries",
   "description": "Broken down by status code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total{proxy=~\"consul-api-proxy.*\"}[1m]))"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU (V1)",
   "type": "timeseries",
   "description": "Percent of CPU used out of total available on Nomad clients",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (task) (nomad_client_allocs_cpu_total_percent{exported_job=~\"bridge\", task!~\"connect-proxy.*\"}) / scalar(count(count(nomad_client_allocs_cpu_total_percent{instance=~\".*\"}) by (instance))) / (8 * .80)"
    }
   ]
  },
  {
   "title": "Mem (V1)",
   "type": "timeseries",
   "description": "Percent of total available memory used per task",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (task) (nomad_client_allocs_memory_usage{exported_job=~\"bridge\", task!~\"connect-proxy.*\"}) / scalar(sum(nomad_client_host_memory_total))"
    },
    {
     "expr": "sum(nomad_client_allocs_memory_usage{exported_job=~\"bridge\", task!~\"connect-proxy.*\"}) / scalar(sum(nomad_client_host_memory_total))"
    },
    {
     "expr": "sum(nomad_client_allocs_memory_allocated{exported_job=~\"bridge\", task!~\"connect-proxy.*\"}) / scalar(sum(nomad_client_host_memory_total))"
    }
   ]
  },
  {
   "title": "CPU (V2)",
   "type": "timeseries",
   "description": "Percent of CPU used out of total available on Nomad clients",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (task) (nomad_client_allocs_cpu_total_percent{exported_job=~\"api-proxy|relay|waku\", task!~\"connect-proxy.*\"}) / scalar(count(count(nomad_client_allocs_cpu_total_percent{instance=~\".*\"}) by (instance))) / (8 * .80)"
    }
   ]
  },
  {
   "title": "Mem (V2)",
   "type": "timeseries",
   "description": "Percent of total available memory used per task",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (task) (nomad_client_allocs_memory_usage{exported_job=~\"api-proxy|relay|waku\", task!~\"connect-proxy.*\"}) / scalar(sum(nomad_client_host_memory_total))"
    },
    {
     "expr": "sum(nomad_client_allocs_memory_usage{exported_job=~\"api-proxy|relay|waku\", task!~\"connect-proxy.*\"}) / scalar(sum(nomad_client_host_memory_total))"
    },
    {
     "expr": "sum(nomad_client_allocs_memory_allocated{exported_job=~\"api-proxy|relay|waku\", task!~\"connect-proxy.*\"}) / scalar(sum(nomad_client_host_memory_total))"
    }
   ]
  }
 ]
}